# Generated by Django 5.2.12 on 2026-03-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='endpoint_or_path',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='region',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='status',
        ),
        migrations.AddField(
            model_name='resource',
            name='runtime_version',
            field=models.CharField(blank=True, help_text='Versão do runtime, ex: python3.12.0, nodejs20.x', max_length=100),
        ),
    ]
