# Generated by Django 5.2.12 on 2026-03-19 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_add_runtime_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='runtime_version',
            field=models.CharField(blank=True, help_text='Ex: python3.12.0, nodejs20.x', max_length=100, verbose_name='Versão do runtime'),
        ),
        migrations.CreateModel(
            name='DatabaseQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição explicativa')),
                ('query_text', models.TextField(verbose_name='Query')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_queries', to='resources.resource')),
            ],
            options={
                'verbose_name': 'Query do Banco',
                'verbose_name_plural': 'Queries do Banco',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da tabela')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_tables', to='resources.resource')),
            ],
            options={
                'verbose_name': 'Tabela do Banco',
                'verbose_name_plural': 'Tabelas do Banco',
                'ordering': ['order', 'name'],
                'unique_together': {('resource', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do campo')),
                ('data_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de dados')),
                ('is_primary_key', models.BooleanField(default=False, verbose_name='Chave primária')),
                ('is_nullable', models.BooleanField(default=True, verbose_name='Permite nulo')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='resources.databasetable')),
            ],
            options={
                'verbose_name': 'Campo da Tabela',
                'verbose_name_plural': 'Campos da Tabela',
                'ordering': ['order', 'name'],
                'unique_together': {('table', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TableRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('one_to_one', 'Um para um'), ('one_to_many', 'Um para muitos'), ('many_to_one', 'Muitos para um'), ('many_to_many', 'Muitos para muitos')], default='one_to_many', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_as_source', to='resources.tablefield')),
                ('source_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='resources.databasetable')),
                ('target_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_as_target', to='resources.tablefield')),
                ('target_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='resources.databasetable')),
            ],
            options={
                'verbose_name': 'Relacionamento entre Tabelas',
                'verbose_name_plural': 'Relacionamentos entre Tabelas',
                'ordering': ['source_table', 'target_table'],
            },
        ),
    ]
