# Generated by Django 5.2.12 on 2026-03-20 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resource_has_pentest_resource_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiGatewayEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, verbose_name='Caminho')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_endpoints', to='resources.resource')),
            ],
            options={
                'verbose_name': 'Endpoint API',
                'verbose_name_plural': 'Endpoints API',
                'ordering': ['order', 'path'],
                'unique_together': {('resource', 'path')},
            },
        ),
        migrations.CreateModel(
            name='ApiGatewayEndpointMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], max_length=10, verbose_name='Método HTTP')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='resources.apigatewayendpoint')),
            ],
            options={
                'verbose_name': 'Método do Endpoint',
                'verbose_name_plural': 'Métodos do Endpoint',
                'ordering': ['order', 'http_method'],
                'unique_together': {('endpoint', 'http_method')},
            },
        ),
        migrations.CreateModel(
            name='ApiGatewayExampleCurl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Rótulo')),
                ('curl_command', models.TextField(verbose_name='Comando curl')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_curls', to='resources.apigatewayendpointmethod')),
            ],
            options={
                'verbose_name': 'Exemplo curl',
                'verbose_name_plural': 'Exemplos curl',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ApiGatewayInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invocations', to='resources.apigatewayendpointmethod')),
                ('target_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoked_by_api_methods', to='resources.resource')),
            ],
            options={
                'verbose_name': 'Invocação API',
                'verbose_name_plural': 'Invocações API',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ApiGatewayPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('request', 'Request'), ('response', 'Response')], max_length=10, verbose_name='Direção')),
                ('content_type', models.CharField(default='application/json', max_length=100, verbose_name='Content-Type')),
                ('body', models.TextField(blank=True, verbose_name='Exemplo/Schema')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='resources.apigatewayendpointmethod')),
            ],
            options={
                'verbose_name': 'Payload API',
                'verbose_name_plural': 'Payloads API',
                'ordering': ['order', 'direction'],
            },
        ),
        migrations.CreateModel(
            name='ApiGatewayParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('param_in', models.CharField(choices=[('path', 'Path'), ('query', 'Query'), ('header', 'Header')], max_length=10, verbose_name='Local')),
                ('param_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo')),
                ('required', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='resources.apigatewayendpointmethod')),
            ],
            options={
                'verbose_name': 'Parâmetro API',
                'verbose_name_plural': 'Parâmetros API',
                'ordering': ['order', 'name'],
                'unique_together': {('method', 'name', 'param_in')},
            },
        ),
    ]
