# Generated by Django 5.2.12

import django.db.models.deletion
from django.db import migrations, models


def migrate_runtime_to_lambda_details(apps, schema_editor):
    """Migra runtime_version de Resource para LambdaDetails em recursos Lambda."""
    Resource = apps.get_model("resources", "Resource")
    ResourceType = apps.get_model("resources", "ResourceType")
    LambdaDetails = apps.get_model("resources", "LambdaDetails")

    rt_lambda = ResourceType.objects.filter(slug="lambda").first()
    if not rt_lambda:
        return

    for resource in Resource.objects.filter(resource_type=rt_lambda):
        runtime = getattr(resource, "runtime_version", "") or ""
        LambdaDetails.objects.get_or_create(
            resource=resource,
            defaults={"runtime_version": runtime},
        )


def reverse_migrate(apps, schema_editor):
    """Restaura runtime_version em Resource a partir de LambdaDetails (para rollback)."""
    Resource = apps.get_model("resources", "Resource")
    LambdaDetails = apps.get_model("resources", "LambdaDetails")

    for ld in LambdaDetails.objects.select_related("resource").all():
        ld.resource.runtime_version = ld.runtime_version
        ld.resource.save()


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0005_add_api_gateway_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="LambdaDetails",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "runtime_version",
                    models.CharField(
                        blank=True,
                        help_text="Ex: python3.12.0, nodejs20.x",
                        max_length=100,
                        verbose_name="Versão do runtime",
                    ),
                ),
                (
                    "example_invocation_payload",
                    models.TextField(
                        blank=True,
                        help_text="JSON de exemplo para invocar a Lambda (teste direto, EventBridge, etc.)",
                        verbose_name="Payload de exemplo para invocação",
                    ),
                ),
                (
                    "mermaid_diagram",
                    models.TextField(
                        blank=True,
                        help_text="Diagrama Mermaid (flowchart, sequence, etc.) do fluxo de execução da Lambda",
                        verbose_name="Diagrama Mermaid de processo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lambda_details",
                        to="resources.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalhes Lambda",
                "verbose_name_plural": "Detalhes Lambda",
            },
        ),
        migrations.RunPython(migrate_runtime_to_lambda_details, reverse_migrate),
        migrations.RemoveField(
            model_name="resource",
            name="runtime_version",
        ),
    ]
