# Generated by Django 5.2.12 on 2026-03-19 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('invokes', 'Invokes'), ('publishes_to', 'Publishes to'), ('subscribes_to', 'Subscribes to'), ('reads_from', 'Reads from'), ('writes_to', 'Writes to'), ('persists_in', 'Persists in'), ('consumes_from', 'Consumes from'), ('exposes', 'Exposes'), ('routes_to', 'Routes to'), ('depends_on', 'Depends on'), ('calls', 'Calls'), ('triggers', 'Triggers'), ('sends_to', 'Sends to'), ('receives_from', 'Receives from')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='resources.resource')),
                ('target_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='resources.resource')),
            ],
            options={
                'verbose_name': 'Relacionamento',
                'verbose_name_plural': 'Relacionamentos',
                'ordering': ['-created_at'],
                'unique_together': {('source_resource', 'relationship_type', 'target_resource')},
            },
        ),
    ]
